"""The one figure. Generated from committed results, like every table.

The six-population ordering is the paper's most-cited result and it was
carried entirely by a table, where the thing worth seeing -- that controlling
for task mix moves some populations a long way and leaves the ordering's
meaning intact -- has to be reconstructed by the reader from two blocks of
numbers.

Run via `make figures`. Writes paper/fig_populations.pdf.
"""
from __future__ import annotations

import json
import pathlib
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
OUT = REPO / "paper"

# Two greys and one accent. The figure has to survive a monochrome printout,
# and the only distinction that carries meaning is run-versus-read, so that is
# the only distinction the colour makes.
READ = "#8c8c8c"
RUN = "#1f4e79"
MODEL = "#c1553b"


def load(path, what):
    p = pathlib.Path(path)
    if not p.exists():
        raise SystemExit(f"missing input: {p}\n  regenerate with: {what}")
    return json.loads(p.read_text())


def main():
    cc = load(RESULTS / "cross_corpus_redos.json", "make crosscorpus")
    anch = load(RESULTS / "anchored_models.json",
                "python3 runner/anchored_models.py --run sweep")

    corpora = {k.split(" (")[0]: v for k, v in cc["corpora"].items()}
    unanchored = [
        ("NL-RX-Synth (grammar control)", corpora["NL-RX-Synth"], READ),
        ("RegexLib", corpora["RegexLib"], READ),
        ("KB13 gold", corpora["KB13"], READ),
        ("Re(gEx|DoS)Eval gold", corpora["RegexEval gold"], READ),
        ("This work, 11 models", anch["pooled"]["unrestricted"], MODEL),
        ("Stack Overflow", corpora["Stack Overflow"], READ),
        ("Production code", corpora["Production code"], RUN),
    ]
    anchored = [
        ("RegexLib", cc["anchored"]["RegexLib, anchored"], READ),
        ("Stack Overflow", cc["anchored"]["Stack Overflow, anchored"], READ),
        ("Re(gEx|DoS)Eval gold", cc["anchored"]["RegexEval gold, anchored"], READ),
        ("This work, 11 models", anch["pooled"]["outputs"], MODEL),
        ("Production code", cc["anchored"]["Production code, anchored"], RUN),
    ]

    fig, axes = plt.subplots(1, 2, figsize=(9.6, 3.4), sharex=True)
    for ax, (title, block) in zip(axes, [("All patterns", unanchored),
                                         ("Anchored ^...$ only", anchored)]):
        block = sorted(block, key=lambda r: r[1]["rate_pct"])
        labels = [f"{name}  (n={row['n']:,})" for name, row, _ in block]
        values = [row["rate_pct"] for _, row, _ in block]
        errors = [row["ci95_pct"] for _, row, _ in block]
        colours = [c for _, _, c in block]
        positions = range(len(block))
        ax.barh(positions, values, xerr=errors, color=colours, height=0.62,
                error_kw={"ecolor": "#333333", "elinewidth": 0.9, "capsize": 2.5})
        ax.set_yticks(list(positions))
        ax.set_yticklabels(labels, fontsize=8)
        ax.set_title(title, fontsize=10, loc="left")
        ax.set_xlabel("ReDoS-screened vulnerable (%)", fontsize=9)
        ax.tick_params(axis="x", labelsize=8)
        ax.grid(axis="x", color="#dddddd", linewidth=0.6)
        ax.set_axisbelow(True)
        for spine in ("top", "right", "left"):
            ax.spines[spine].set_visible(False)
        for pos, value in zip(positions, values):
            ax.text(value + 1.4, pos, f"{value:.1f}", va="center", fontsize=8)
        ax.set_xlim(0, max(values) * 1.28)

    handles = [plt.Rectangle((0, 0), 1, 1, color=c) for c in (READ, RUN, MODEL)]
    fig.legend(handles, ["written to be read", "executed in shipped packages",
                         "generated by the models here"],
               loc="lower center", ncol=3, frameon=False, fontsize=8.5,
               bbox_to_anchor=(0.5, -0.06))
    fig.tight_layout()
    path = OUT / "fig_populations.pdf"
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(OUT / "fig_populations.png", dpi=170, bbox_inches="tight")
    print(f"wrote {path}")


if __name__ == "__main__":
    sys.exit(main())
